---
apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Asset
metadata:
  name: {{ .Values.device.name | default "device-001" }}
  namespace: {{ default "azure-iot-operations" }}
spec:
  deviceRef:
    deviceName: {{ .Values.device.name | default "device-001" }}
    endpointName: {{ .Values.device.inboundEndpoint.name | default "device-001-endpoint" }}
  version: 1
  {{ .Values.datasets }}
