# The Akri operator will use the connector config to deploy your connector as a Kubernetes pod when a matching AEP has been created on the cluster
# Documentation: https://github.com/Azure/azure-iot-operations-preview/blob/main/preview/akri-connectors/docs/akri-configurations.md#connector-configuration
---
apiVersion: akri.microsoft.com/v1beta1
kind: ConnectorConfig
metadata:
  name: '{{ .Values.asset.name | default "device-001" }}-aio-connector-config'
  namespace: {{ .Values.namespace | default "azure-iot-operations" }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  assetEndpointProfileType: {{ .Values.assetEndpointProfile.type | default "device-type-001" }}
  # The image to use for the connector application
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
