---
apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Asset
metadata:
  name: {{ .Values.assetName }}
  namespace: {{ default "azure-iot-operations" }}
spec:
  deviceRef:
    deviceName: {{ .Values.assetName }}
    endpointName: "{{ .Values.assetName }}-endpoint"
  version: 1
  {{ .Values.datasets }}
