---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.asset.name | default "device-001" }}-aio-connector-aep-creds'
  namespace: {{ .Values.namespace | default "azure-iot-operations" }}
type: Opaque
data:
  username: {{ randAlpha 5 | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
