---
apiVersion: akri.microsoft.com/v1beta1
kind: ConnectorTemplate
metadata:
  name: "{{ .Values.assetName }}-aio-connector-template"
  namespace: {{ default "azure-iot-operations" }}
spec:
   version: "0.0.1"
   deviceInboundEndpointTypes:
   - endpointType: "{{ .Values.assetName }}-endpoint-type"
     version: "0.0.1"
   runtimeConfiguration:
     runtimeConfigurationType: managedConfiguration
     managedConfigurationSettings:
      managedConfigurationType: imageConfiguration
      imageConfigurationSettings:
        imageName: {{ .Values.image.repository }}
        imagePullPolicy: Always # This sample image is built locally, so no need to pull
        replicas: {{ .Values.replicas | default 1 }}
        tagDigestSettings:
          tagDigestType: tag
          tag: {{ .Values.image.tag | default .Chart.AppVersion }}
   mqttConnectionConfiguration:
     host: {{ .Values.mqttConnectionConfigurationHost }}
     authentication:
      method: ServiceAccountToken
      serviceAccountTokenSettings:
        audience: aio-internal
     tls:
       mode: Enabled
       trustedCaCertificateConfigMapRef: azure-iot-operations-aio-ca-trust-bundle
