---
apiVersion: v1
kind: Secret
metadata:
  name: aio-dds-connector-aep-creds
  namespace: {{ .Values.namespace | default "azure-iot-operations" }}
type: Opaque
data:
  username: dXNlcjE=
  password: dXNlcjE=