datasets:
  - name: thermodynamics
    dataSource: /thermostat
    datasetConfiguration: |-
      {
        "samplingInterval": 5000
      }
    destinations:
      - configuration:
          topic: azure-iot-operations/data/device-001/currentAmbientTemperature
        target: Mqtt
    dataPoints:
      - dataSource: /piwebapi/assetservers/F1RSCf1onAl8tkuTYgE2NfIPFQQVZFVkFQSQ/assetdatabases
        name: genericDataPoint
      - dataSource: /piwebapi/assetservers/F1RSCf1onAl8tkuTYgE2NfIPFQQVZFVkFQSQ/assetdatabases
        name: verySpecificDataPoint
  - name: pneumatics
    dataSource: /thermostat
    datasetConfiguration: |-
      {
        "samplingInterval": 10000
      }
    destinations:
      - configuration:
          topic: azure-iot-operations/data/device-001/currentAmbientPressure
        target: Mqtt
    dataPoints:
      - dataSource: /piwebapi/assetdatabases/F1RDCf1onAl8tkuTYgE2NfIPFQNp0AsaE7302XMsysUw2j2gQVZFVkFQSVxERUZBVUxUVVNFUkRC/elements
        name: genericDataPoint
